apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "m2repo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "12-factor-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/redhat-developer-demos/the-deploy-master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"